FROM node:24-alpine AS builder

WORKDIR /user

COPY package*.json ./
COPY *.tgz ./

RUN npm install ./kshitij_npm-sell_db-1.1.0.tgz ./kshitij_npm-sell_auth-1.1.0.tgz && npm install

COPY . .

# RUN npx drizzle-kit push --config ./db/drizzle.config.ts

RUN npm run build 

FROM node:24-alpine

WORKDIR /user

COPY --from=builder /user/dist ./dist
COPY --from=builder /user/package*.json ./
COPY --from=builder /user/node_modules ./node_modules

EXPOSE 4000

CMD ["npm", "start"]
